### Pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
seriesData = pd.Series([1, 2, 3, 4,])
seriesData

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
seriesData.dtype

dtype('int64')

In [4]:
dataframeData = pd.DataFrame([[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]])
dataframeData

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [5]:
dataframeData = pd.DataFrame([[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]], columns=['a', 'b', 'c'])
dataframeData

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [6]:
dataframeData = pd.DataFrame([[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]])
dataframeData

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [7]:
dataframeData.rename(columns={0:'a',
                              1:'b',
                              2:'c'}, inplace=True)
dataframeData

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [10]:
value = np.random.randint(10, 40,(20, 3))
print(value)

[[37 36 27]
 [14 32 35]
 [31 20 12]
 [21 35 33]
 [13 38 35]
 [20 20 26]
 [38 27 33]
 [34 30 30]
 [23 16 38]
 [29 17 13]
 [13 34 23]
 [25 11 16]
 [26 12 30]
 [34 31 28]
 [38 28 10]
 [33 29 20]
 [13 24 35]
 [29 20 28]
 [35 27 28]
 [34 17 29]]


In [13]:
df = pd.DataFrame(value, columns=['harga', 'berat', 'umur'])
df

harga  berat  umur
0      37     36    27
1      14     32    35
2      31     20    12
3      21     35    33
4      13     38    35
5      20     20    26
6      38     27    33
7      34     30    30
8      23     16    38
9      29     17    13
10     13     34    23
11     25     11    16
12     26     12    30
13     34     31    28
14     38     28    10
15     33     29    20
16     13     24    35
17     29     20    28
18     35     27    28
19     34     17    29

#### Accessing iloc and loc

#### Modify data

#### Sorting data

#### Filtering data

#### Adding and remove columns

In [1]:
import pandas as pd
import numpy as np

In [4]:
contohNumpy = np.array([1, 2, 3, 4])
print(contohNumpy)

[1 2 3 4]


In [2]:
contohSeries = pd.Series([1, 2, 3, 4])
contohSeries

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
contohSeries[2]

3

In [7]:
contohSeries[0:3]

0    1
1    2
2    3
dtype: int64

In [8]:
contohSeries = pd.Series([5, 6, 7, 8], index=['a', 'b', 'c', 'd'])
contohSeries

a    5
b    6
c    7
d    8
dtype: int64

In [9]:
contohSeries['a':'c']

a    5
b    6
c    7
dtype: int64

In [10]:
contohSeries = pd.Series([1, 2, 3, 4])
contohSeries

0    1
1    2
2    3
3    4
dtype: int64

In [14]:
contohSeries.index = ['a', 'b', 'c', 'd']
contohSeries

a    1
b    2
c    3
d    4
dtype: int64

In [15]:
contohDataframe = pd.DataFrame([[2, 4],
                               [5, 7],
                               [8, 0],
                               [1, 7]])
contohDataframe


0  1
0  2  4
1  5  7
2  8  0
3  1  7

In [18]:
hasilPenjualan = pd.DataFrame([['jeruk', 10000, 8000],
                                ['apel', 20000, 15_000],
                                ['anggur', 15000, 12000],
                                ['mangga', 18000, 10000],
                                ['melon', 20000, 12000],
                                ['semangka', 12000, 11000]], columns=['nama buah', 'harga jual', 'harga beli'])
hasilPenjualan

nama buah  harga jual  harga beli
0     jeruk       10000        8000
1      apel       20000       15000
2    anggur       15000       12000
3    mangga       18000       10000
4     melon       20000       12000
5  semangka       12000       11000

In [19]:
hasilPenjualan.head(3)

nama buah  harga jual  harga beli
0     jeruk       10000        8000
1      apel       20000       15000
2    anggur       15000       12000

In [20]:
hasilPenjualan.dtypes

nama buah     object
harga jual     int64
harga beli     int64
dtype: object

In [23]:
# Check informasi dataset
hasilPenjualan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   nama buah   6 non-null      object
 1   harga jual  6 non-null      int64 
 2   harga beli  6 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes


In [ ]:
# Check nama kolom
hasilPenjualan.columns

Index(['nama buah', 'harga jual', 'harga beli'], dtype='object')

In [25]:
print(f'Jumlah baris {hasilPenjualan.shape[0]}')
print(f"Jumlah kolom {hasilPenjualan.shape[1]}")

Jumlah baris 6
Jumlah kolom 3


In [26]:
hasilPenjualan

nama buah  harga jual  harga beli
0     jeruk       10000        8000
1      apel       20000       15000
2    anggur       15000       12000
3    mangga       18000       10000
4     melon       20000       12000
5  semangka       12000       11000

In [27]:
hasilPenjualan['harga jual']

0    10000
1    20000
2    15000
3    18000
4    20000
5    12000
Name: harga jual, dtype: int64

In [30]:
hasilPenjualan.rename(columns={'nama buah':'nama_buah',
                               'harga jual':'harga_jual',
                               'harga beli':'harga_beli'}, inplace=True)
hasilPenjualan

nama_buah  harga_jual  harga_beli
0     jeruk       10000        8000
1      apel       20000       15000
2    anggur       15000       12000
3    mangga       18000       10000
4     melon       20000       12000
5  semangka       12000       11000

In [31]:
hasilPenjualan.columns

Index(['nama_buah', 'harga_jual', 'harga_beli'], dtype='object')

In [32]:
hasilPenjualan.harga_jual

0    10000
1    20000
2    15000
3    18000
4    20000
5    12000
Name: harga_jual, dtype: int64

In [33]:
hasilPenjualan["harga_jual"]

0    10000
1    20000
2    15000
3    18000
4    20000
5    12000
Name: harga_jual, dtype: int64

In [35]:
hasilPenjualan

nama_buah  harga_jual  harga_beli
0     jeruk       10000        8000
1      apel       20000       15000
2    anggur       15000       12000
3    mangga       18000       10000
4     melon       20000       12000
5  semangka       12000       11000

In [42]:
round(hasilPenjualan['harga_jual'].mean(),2)

15833.33

In [44]:
hasilPenjualan.iloc[2]

nama_buah     anggur
harga_jual     15000
harga_beli     12000
Name: 2, dtype: object

In [45]:
hasilPenjualan.iloc[2:5]

nama_buah  harga_jual  harga_beli
2    anggur       15000       12000
3    mangga       18000       10000
4     melon       20000       12000

In [47]:
hasilPenjualan[hasilPenjualan['harga_jual'] < 20000]

nama_buah  harga_jual  harga_beli
0     jeruk       10000        8000
2    anggur       15000       12000
3    mangga       18000       10000
5  semangka       12000       11000

In [48]:
hasilPenjualan['laba'] = hasilPenjualan['harga_jual'] - hasilPenjualan['harga_beli']
hasilPenjualan

nama_buah  harga_jual  harga_beli  laba
0     jeruk       10000        8000  2000
1      apel       20000       15000  5000
2    anggur       15000       12000  3000
3    mangga       18000       10000  8000
4     melon       20000       12000  8000
5  semangka       12000       11000  1000

In [49]:
hasilPenjualan.sort_values(by='laba', ascending=False)

nama_buah  harga_jual  harga_beli  laba
3    mangga       18000       10000  8000
4     melon       20000       12000  8000
1      apel       20000       15000  5000
2    anggur       15000       12000  3000
0     jeruk       10000        8000  2000
5  semangka       12000       11000  1000

In [53]:
buahBulat = hasilPenjualan[(hasilPenjualan['nama_buah'] == 'melon') | (hasilPenjualan['nama_buah'] == 'semangka') ]

In [54]:
buahBulat

nama_buah  harga_jual  harga_beli  laba
4     melon       20000       12000  8000
5  semangka       12000       11000  1000

In [55]:
buahBulat.T

4         5
nama_buah   melon  semangka
harga_jual  20000     12000
harga_beli  12000     11000
laba         8000      1000

In [57]:
buahBulat.reset_index(drop='index')

nama_buah  harga_jual  harga_beli  laba
0     melon       20000       12000  8000
1  semangka       12000       11000  1000

In [59]:
hasilPenjualan.isnull().sum()

nama_buah     0
harga_jual    0
harga_beli    0
laba          0
dtype: int64

In [60]:
hasilPenjualan

nama_buah  harga_jual  harga_beli  laba
0     jeruk       10000        8000  2000
1      apel       20000       15000  5000
2    anggur       15000       12000  3000
3    mangga       18000       10000  8000
4     melon       20000       12000  8000
5  semangka       12000       11000  1000

In [67]:
hasilPenjualan.iloc[4,3] = np.nan

In [68]:
hasilPenjualan

nama_buah  harga_jual  harga_beli    laba
0     jeruk       10000        8000  2000.0
1      apel       20000       15000  5000.0
2    anggur       15000       12000  3000.0
3    mangga       18000       10000  8000.0
4     melon       20000       12000     NaN
5  semangka       12000       11000  1000.0

In [70]:
hasilPenjualan.isnull().sum()

nama_buah     0
harga_jual    0
harga_beli    0
laba          1
dtype: int64